// frontend/src/components/PinEntry.vue
<template>
  <div class="pin-entry fade-in">
    <div class="casino-card table-marking">
      <h1 class="casino-title">TAKE A SEAT</h1>
      <form @submit.prevent="joinSession" class="join-form">
        <div class="form-group">
          <label for="pin">TABLE PIN</label>
          <input
            id="pin"
            v-model="pin"
            type="text"
            class="casino-input pin-input"
            placeholder="000000"
            maxlength="6"
            pattern="[0-9]{6}"
            required
            @input="formatPin"
          />
        </div>
        <div class="form-group">
          <label for="name">PLAYER NAME</label>
          <input
            id="name"
            v-model="name"
            type="text"
            class="casino-input"
            placeholder="e.g. Maverick"
            required
          />
        </div>
        <button type="submit" class="casino-button" :disabled="loading || pin.trim().length !== 6">
          {{ loading ? 'SITTING DOWN...' : 'JOIN TABLE' }}
        </button>
        <p v-if="error" class="error-message">{{ error }}</p>
      </form>
    </div>
  </div>
</template>

<script>
import { sessionService } from '../services/apiService'

export default {
  name: 'PinEntry',
  props: {
    initialPin: {
      type: String,
      default: ''
    }
  },
  data() {
    return {
      pin: this.initialPin,
      name: '',
      loading: false,
      error: ''
    }
  },
  methods: {
    formatPin(event) {
      let value = event.target.value.replace(/\D/g, '')
      if (value.length > 6) {
        value = value.substring(0, 6)
      }
      this.pin = value
      this.error = ''
    },
    async joinSession() {
      if (this.pin.length !== 6 || !this.name.trim()) return
      
      this.loading = true
      this.error = ''
      
      try {
        // First verify session exists
        await sessionService.getSession(this.pin)
        
        // Join the session
        const participant = await sessionService.joinSession(this.pin, this.name)
        
        // Navigate to session
        this.$router.push({
          path: `/session/${this.pin}`,
          query: { participantId: participant.participantId, name: this.name }
        })
      } catch (error) {
        console.error('Error joining session:', error)
        if (error.response?.status === 404) {
          this.error = 'Session not found. Please check the PIN.'
        } else {
          this.error = 'Failed to join session. Please try again.'
        }
      } finally {
        this.loading = false
      }
    }
  }
}
</script>

<style scoped>
.pin-entry {
  display: flex;
  justify-content: center;
  padding: 20px;
}

.casino-title {
  font-size: 32px;
  color: #d4af37;
  text-align: center;
  margin-bottom: 40px;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
  font-family: 'Georgia', serif;
  letter-spacing: 2px;
}

.form-group label {
  display: block;
  margin-bottom: 12px;
  color: #f5d76e;
  font-weight: 900;
  letter-spacing: 1px;
}

.pin-input {
  text-align: center;
  font-size: 42px;
  letter-spacing: 12px;
  font-weight: 900;
  color: #d4af37 !important;
  font-family: 'Courier New', monospace;
}

.error-message {
  color: #ff6b6b;
  margin-top: 20px;
  text-align: center;
  font-size: 14px;
  font-weight: bold;
  background: rgba(0,0,0,0.3);
  padding: 10px;
  border-radius: 4px;
}
</style>

// frontend/src/components/PinEntry.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { sessionService } from '../services/apiService';

interface PinEntryProps {
  initialPin?: string;
}

const PinEntry: React.FC<PinEntryProps> = ({ initialPin = '' }) => {
  const [pin, setPin] = useState(initialPin);
  const [name, setName] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const formatPin = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value = e.target.value.replace(/\D/g, '');
    if (value.length > 6) {
      value = value.substring(0, 6);
    }
    setPin(value);
    setError('');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (pin.length !== 6 || !name.trim()) return;

    setLoading(true);
    setError('');

    try {
      // First verify session exists
      await sessionService.getSession(pin);

      // Join the session
      const participant = await sessionService.joinSession(pin, name);

      // Navigate to session
      navigate(`/session/${pin}?participantId=${participant.participantId}&name=${encodeURIComponent(name)}`);
    } catch (err: any) {
      console.error('Error joining session:', err);
      if (err.response?.status === 404) {
        setError('Session not found. Please check the PIN.');
      } else {
        setError('Failed to join session. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="pin-entry fade-in">
      <div className="casino-card table-marking">
        <h1 className="casino-title">TAKE A SEAT</h1>
        <form onSubmit={handleSubmit} className="join-form">
          <div className="form-group">
            <label htmlFor="pin">TABLE PIN</label>
            <input
              id="pin"
              value={pin}
              onChange={formatPin}
              type="text"
              className="casino-input pin-input"
              placeholder="000000"
              maxLength={6}
              pattern="[0-9]{6}"
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="name">PLAYER NAME</label>
            <input
              id="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              type="text"
              className="casino-input"
              placeholder="e.g. Maverick"
              required
            />
          </div>
          <button type="submit" className="casino-button" disabled={loading || pin.trim().length !== 6}>
            {loading ? 'SITTING DOWN...' : 'JOIN TABLE'}
          </button>
          {error && <p className="error-message">{error}</p>}
        </form>
      </div>
    </div>
  );
};

export default PinEntry;
