// frontend/src/components/VotingRoom.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import PlayingCard from './PlayingCard';
import ResultsDisplay from './ResultsDisplay';
import { sessionService } from '../services/apiService';
import signalrService from '../services/signalrService';
import { Participant, Results } from '../types';

interface VotingRoomProps {
  pin: string;
  currentParticipantId: number | null;
  currentParticipantName: string;
  isHost: boolean;
}

const VotingRoom: React.FC<VotingRoomProps> = ({
  pin,
  currentParticipantId,
  currentParticipantName,
  isHost,
}) => {
  const navigate = useNavigate();
  const [sessionName, setSessionName] = useState('');
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [selectedCard, setSelectedCard] = useState('');
  const [votes, setVotes] = useState<Record<number, string>>({});
  const [isRevealed, setIsRevealed] = useState(false);
  const [results, setResults] = useState<Results | null>(null);
  const [showEndConfirm, setShowEndConfirm] = useState(false);

  const cardValues = ['0', '1', '2', '3', '5', '8', '13', '21', '∞'];

  const loadSession = useCallback(async () => {
    try {
      const session = await sessionService.getSession(pin);
      setSessionName(session.sessionName);
      setParticipants(session.participants || []);
    } catch (error) {
      console.error('Error loading session:', error);
    }
  }, [pin]);

  const loadResults = useCallback(async () => {
    try {
      const res = await sessionService.getResults(pin);
      setResults(res);
      const newVotes: Record<number, string> = {};
      res.votes.forEach((vote) => {
        newVotes[vote.participantId] = vote.cardValue;
      });
      setVotes(newVotes);
    } catch (error) {
      console.error('Error loading results:', error);
    }
  }, [pin]);

  const handleNewRoundStarted = useCallback(() => {
    setIsRevealed(false);
    setSelectedCard('');
    setVotes({});
    setResults(null);
  }, []);

  useEffect(() => {
    const setup = async () => {
      await loadSession();
      try {
        await signalrService.connect();
        await signalrService.joinSession(pin, currentParticipantName || 'Participant');

        signalrService.onParticipantJoined(() => {
          loadSession();
        });

        signalrService.onVoteSubmitted((data) => {
          setVotes((prev) => ({ ...prev, [data.participantId]: data.cardValue }));
        });

        signalrService.onVotesRevealed(async () => {
          setIsRevealed(true);
          await loadResults();
        });

        signalrService.onNewRoundStarted(() => {
          handleNewRoundStarted();
        });

        signalrService.onSessionEnded(() => {
          navigate('/');
        });
      } catch (error) {
        console.error('Error setting up SignalR:', error);
      }
    };

    setup();

    return () => {
      signalrService.off('ParticipantJoined');
      signalrService.off('VoteSubmitted');
      signalrService.off('VotesRevealed');
      signalrService.off('NewRoundStarted');
      signalrService.off('SessionEnded');
      if (pin) {
        signalrService.leaveSession(pin);
      }
    };
  }, [pin, currentParticipantName, loadSession, loadResults, handleNewRoundStarted]);

  const selectCard = async (cardValue: string) => {
    if (!currentParticipantId || isRevealed) return;

    setSelectedCard(cardValue);
    try {
      await sessionService.submitVote(pin, currentParticipantId, cardValue);
      setVotes((prev) => ({ ...prev, [currentParticipantId]: cardValue }));
    } catch (error) {
      console.error('Error submitting vote:', error);
      alert('Failed to submit vote. Please try again.');
    }
  };

  const revealVotes = async () => {
    try {
      await sessionService.revealVotes(pin);
      setIsRevealed(true);
      await loadResults();
    } catch (error) {
      console.error('Error revealing votes:', error);
    }
  };

  const startNewRound = async () => {
    if (!isHost) return;
    try {
      await sessionService.resetSession(pin);
    } catch (error) {
      console.error('Error resetting session:', error);
      alert('Failed to start new round. Please try again.');
    }
  };

  const endSession = async () => {
    if (!isHost) return;
    setShowEndConfirm(true);
  };

  const confirmEndSession = async () => {
    try {
      await sessionService.endSession(pin);
    } catch (error) {
      console.error('Error ending session:', error);
    } finally {
      setShowEndConfirm(false);
    }
  };

  const hasVoted = (participantId: number) => {
    return votes[participantId] !== undefined;
  };

  return (
    <div className="voting-room home bg-area">
      <div className="session-header table-marking">
        <h1 className="session-name">{sessionName}</h1>
        <div className="session-pin">SESSION ID: {pin}</div>
      </div>

      <div className="participants-section">
        <h2 className="section-title">Players at Table ({participants.length})</h2>
        <div className="participants-list">
          {participants.map((participant) => (
            <div
              key={participant.participantId}
              className={`participant-item ${hasVoted(participant.participantId) ? 'has-voted' : ''}`}
            >
              <div className="chip-avatar">{participant.name[0].toUpperCase()}</div>
              <span className="participant-name">{participant.name}</span>
              {hasVoted(participant.participantId) && <span className="vote-indicator">READY</span>}
            </div>
          ))}
        </div>
      </div>

      {!isRevealed && (
        <div className="voting-section table-marking">
          <h2 className="section-title">Place Your Bet</h2>
          <div className="cards-container">
            {cardValues.map((cardValue) => (
              <PlayingCard
                key={cardValue}
                value={cardValue}
                isSelected={selectedCard === cardValue}
                disabled={!currentParticipantId || isRevealed}
                onSelect={selectCard}
              />
            ))}
          </div>
          {selectedCard && (
            <div className="selected-card-info">
              YOUR CHOICE: <strong>{selectedCard}</strong>
            </div>
          )}
        </div>
      )}

      {isHost && !isRevealed && (
        <div className="host-controls">
          <button
            onClick={revealVotes}
            className="casino-button reveal-button"
            disabled={participants.length === 0}
          >
            Reveal Votes
          </button>
          <button
            onClick={endSession}
            className="casino-button end-session-button"
          >
            End Session
          </button>
        </div>
      )}

      {isRevealed && results && (
        <ResultsDisplay
          votes={results.votes}
          statistics={results.statistics}
          isHost={isHost}
          onNewRound={startNewRound}
          onEndSession={endSession}
        />
      )}

      {showEndConfirm && (
        <div className="modal-overlay">
          <div className="casino-modal">
            <h2 className="modal-title">Close Table?</h2>
            <p className="modal-content">
              Are you sure you want to end the session? This will clear all data and return everyone to the lobby.
            </p>
            <div className="modal-actions">
              <button 
                onClick={() => setShowEndConfirm(false)} 
                className="casino-button modal-button cancel"
              >
                STAY
              </button>
              <button 
                onClick={confirmEndSession} 
                className="casino-button modal-button end-session-button"
              >
                END GAME
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default VotingRoom;

// frontend/src/components/VotingRoom.vue
<template>
  <div class="voting-room">
    <div class="session-header table-marking">
      <h1 class="session-name">{{ sessionName }}</h1>
      <div class="session-pin">SESSION ID: {{ pin }}</div>
    </div>
    
    <div class="participants-section">
      <h2 class="section-title">Players at Table ({{ participants.length }})</h2>
      <div class="participants-list">
        <div
          v-for="participant in participants"
          :key="participant.participantId"
          class="participant-item"
          :class="{ 'has-voted': hasVoted(participant.participantId) }"
        >
          <div class="chip-avatar">{{ participant.name[0].toUpperCase() }}</div>
          <span class="participant-name">{{ participant.name }}</span>
          <span v-if="hasVoted(participant.participantId)" class="vote-indicator">READY</span>
        </div>
      </div>
    </div>
    
    <div v-if="!isRevealed" class="voting-section table-marking">
      <h2 class="section-title">Place Your Bet</h2>
      <div class="cards-container">
        <PlayingCard
          v-for="cardValue in cardValues"
          :key="cardValue"
          :value="cardValue"
          :is-selected="selectedCard === cardValue"
          :disabled="!currentParticipantId || isRevealed"
          @select="selectCard"
        />
      </div>
      <div v-if="selectedCard" class="selected-card-info">
        YOUR CHOICE: <strong>{{ selectedCard }}</strong>
      </div>
    </div>
    
    <div v-if="isHost && !isRevealed" class="host-controls">
      <button
        @click="revealVotes"
        class="casino-button reveal-button"
        :disabled="participants.length === 0"
      >
        Reveal Votes
      </button>
    </div>
    
    <ResultsDisplay
      v-if="isRevealed && results"
      :votes="results.votes"
      :statistics="results.statistics"
      :is-host="isHost"
      @new-round="startNewRound"
    />
  </div>
</template>

<script>
import PlayingCard from './PlayingCard.vue'
import ResultsDisplay from './ResultsDisplay.vue'
import { sessionService } from '../services/apiService'
import signalrService from '../services/signalrService'

export default {
  name: 'VotingRoom',
  components: {
    PlayingCard,
    ResultsDisplay
  },
  props: {
    pin: {
      type: String,
      required: true
    },
    currentParticipantId: {
      type: Number,
      default: null
    },
    currentParticipantName: {
      type: String,
      default: ''
    },
    isHost: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      sessionName: '',
      participants: [],
      selectedCard: '',
      cardValues: ['0', '1', '2', '3', '5', '8', '13', '21', '∞'],
      votes: {},
      isRevealed: false,
      results: null
    }
  },
  async mounted() {
    await this.loadSession()
    await this.setupSignalR()
    await this.loadResults()
  },
  beforeUnmount() {
    signalrService.off('ParticipantJoined')
    signalrService.off('VoteSubmitted')
    signalrService.off('VotesRevealed')
    signalrService.off('NewRoundStarted')
    if (this.pin) {
      signalrService.leaveSession(this.pin)
    }
  },
  methods: {
    async loadSession() {
      try {
        const session = await sessionService.getSession(this.pin)
        this.sessionName = session.sessionName
        this.participants = session.participants || []
      } catch (error) {
        console.error('Error loading session:', error)
      }
    },
    async setupSignalR() {
      try {
        await signalrService.connect()
        await signalrService.joinSession(this.pin, this.currentParticipantName || 'Participant')
        
        signalrService.onParticipantJoined((data) => {
          this.loadSession()
        })
        
        signalrService.onVoteSubmitted((data) => {
          this.votes[data.participantId] = data.cardValue
          this.$forceUpdate()
        })
        
        signalrService.onVotesRevealed(async () => {
          this.isRevealed = true
          await this.loadResults()
        })

        signalrService.onNewRoundStarted(() => {
          this.handleNewRoundStarted()
        })
      } catch (error) {
        console.error('Error setting up SignalR:', error)
      }
    },
    async selectCard(cardValue) {
      if (!this.currentParticipantId || this.isRevealed) return
      
      this.selectedCard = cardValue
      try {
        await sessionService.submitVote(this.pin, this.currentParticipantId, cardValue)
        this.votes[this.currentParticipantId] = cardValue
      } catch (error) {
        console.error('Error submitting vote:', error)
        alert('Failed to submit vote. Please try again.')
      }
    },
    async revealVotes() {
      try {
        await sessionService.revealVotes(this.pin)
        this.isRevealed = true
        await this.loadResults()
      } catch (error) {
        console.error('Error revealing votes:', error)
      }
    },
    async loadResults() {
      try {
        const results = await sessionService.getResults(this.pin)
        this.results = results
        // Update votes map
        results.votes.forEach(vote => {
          this.votes[vote.participantId] = vote.cardValue
        })
      } catch (error) {
        console.error('Error loading results:', error)
      }
    },
    hasVoted(participantId) {
      return this.votes[participantId] !== undefined
    },
    async startNewRound() {
      if (!this.isHost) return
      try {
        await sessionService.resetSession(this.pin)
      } catch (error) {
        console.error('Error resetting session:', error)
        alert('Failed to start new round. Please try again.')
      }
    },
    handleNewRoundStarted() {
      this.isRevealed = false
      this.selectedCard = ''
      this.votes = {}
      this.results = null
    }
  }
}
</script>

<style scoped>
.voting-room {
  padding: 20px;
  max-width: 1400px;
  margin: 0 auto;
}

.session-header {
  text-align: center;
  margin-bottom: 40px;
  background: rgba(0, 0, 0, 0.3);
}

.session-name {
  color: #d4af37;
  font-size: 48px;
  margin-bottom: 5px;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.8);
  font-family: 'Georgia', serif;
  font-variant: small-caps;
}

.session-pin {
  color: #f5d76e;
  font-size: 20px;
  font-weight: 900;
  letter-spacing: 6px;
}

.participants-section {
  margin-bottom: 40px;
}

.section-title {
  color: #f5d76e;
  margin-bottom: 20px;
  font-size: 24px;
  text-transform: uppercase;
  letter-spacing: 2px;
  text-align: center;
  font-family: 'Georgia', serif;
}

.participants-list {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 15px;
}

.participant-item {
  background: rgba(0, 0, 0, 0.4);
  border: 2px solid #d4af37;
  border-radius: 40px;
  padding: 8px 20px 8px 8px;
  display: flex;
  align-items: center;
  gap: 12px;
  transition: all 0.3s ease;
  min-width: 150px;
}

.participant-item.has-voted {
  border-color: #4caf50;
  background: rgba(76, 175, 80, 0.15);
  box-shadow: 0 0 10px rgba(76, 175, 80, 0.3);
}

.chip-avatar {
  width: 36px;
  height: 36px;
  background: linear-gradient(135deg, #d4af37 0%, #b8941f 100%);
  border: 2px dashed #f5d76e;
  border-radius: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
  color: #1a1a1a;
  font-weight: 900;
  box-shadow: 0 2px 4px rgba(0,0,0,0.3);
}

.participant-name {
  color: #f5f5dc;
  font-weight: bold;
  font-size: 16px;
}

.vote-indicator {
  color: #4caf50;
  font-size: 12px;
  font-weight: 900;
  margin-left: auto;
  letter-spacing: 1px;
}

.voting-section {
  margin-bottom: 40px;
  background: rgba(0, 0, 0, 0.2);
}

.cards-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 20px;
  margin-bottom: 30px;
}

.selected-card-info {
  text-align: center;
  color: #f5d76e;
  font-size: 20px;
  margin-top: 30px;
  font-weight: bold;
  letter-spacing: 2px;
  text-transform: uppercase;
}

.host-controls {
  text-align: center;
  margin-top: 30px;
}

.reveal-button {
  font-size: 20px;
  padding: 15px 30px;
}

@media (max-width: 768px) {
  .session-name {
    font-size: 28px;
  }
  
  .session-pin {
    font-size: 18px;
  }
  
  .cards-container {
    gap: 10px;
  }
}
</style>
