// frontend/src/views/Session.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useLocation, useNavigate } from 'react-router-dom';
import VotingRoom from '../components/VotingRoom';
import { sessionService } from '../services/apiService';

const Session: React.FC = () => {
  const { pin } = useParams<{ pin: string }>();
  const location = useLocation();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [participantId, setParticipantId] = useState<number | null>(null);
  const [participantName, setParticipantName] = useState('');
  const [isHost, setIsHost] = useState(false);

  const initializeSession = useCallback(async () => {
    if (!pin) return;

    try {
      const queryParams = new URLSearchParams(location.search);
      const pId = queryParams.get('participantId');
      const name = queryParams.get('name');

      if (pId && name) {
        setParticipantId(parseInt(pId));
        setParticipantName(name);
      }

      const session = await sessionService.getSession(pin);

      if (session.participants && session.participants.length > 0) {
        const firstParticipant = session.participants[0];
        setIsHost(parseInt(pId || '0') === firstParticipant.participantId);
      } else {
        setIsHost(true);
      }

      setLoading(false);
    } catch (err) {
      console.error('Error initializing session:', err);
      setError('Session not found or could not be loaded.');
      setLoading(false);
    }
  }, [pin, location.search]);

  useEffect(() => {
    initializeSession();
  }, [initializeSession]);

  if (loading) {
    return (
      <div className="session-view">
        <div className="loading">
          <p>Loading session...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="session-view">
        <div className="error">
          <p>{error}</p>
          <button onClick={() => navigate('/')} className="casino-button">
            Go Home
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="session-view">
      <VotingRoom
        pin={pin!}
        currentParticipantId={participantId}
        currentParticipantName={participantName}
        isHost={isHost}
      />
    </div>
  );
};

export default Session;

// frontend/src/views/Session.vue
<template>
  <div class="session-view">
    <div v-if="loading" class="loading">
      <p>Loading session...</p>
    </div>
    <div v-else-if="error" class="error">
      <p>{{ error }}</p>
      <button @click="$router.push('/')" class="casino-button">
        Go Home
      </button>
    </div>
    <VotingRoom
      v-else
      :pin="pin"
      :current-participant-id="participantId"
      :current-participant-name="participantName"
      :is-host="isHost"
    />
  </div>
</template>

<script>
import VotingRoom from '../components/VotingRoom.vue'
import { sessionService } from '../services/apiService'

export default {
  name: 'Session',
  components: {
    VotingRoom
  },
  props: {
    pin: {
      type: String,
      required: true
    }
  },
  data() {
    return {
      loading: true,
      error: '',
      participantId: null,
      participantName: '',
      isHost: false,
      sessionCreatorId: null
    }
  },
  async mounted() {
    await this.initializeSession()
  },
  methods: {
    async initializeSession() {
      try {
        // Get participant info from query params if available
        const participantId = this.$route.query.participantId
        const name = this.$route.query.name
        
        if (participantId && name) {
          this.participantId = parseInt(participantId)
          this.participantName = name
        }
        
        // Load session to verify it exists
        const session = await sessionService.getSession(this.pin)
        
        // Check if this is the host (first participant or session creator)
        // For simplicity, we'll consider the first participant as host
        if (session.participants && session.participants.length > 0) {
          const firstParticipant = session.participants[0]
          this.isHost = this.participantId === firstParticipant.participantId
        } else {
          // If no participants yet, allow joining as host
          this.isHost = true
        }
        
        this.loading = false
      } catch (error) {
        console.error('Error initializing session:', error)
        this.error = 'Session not found or could not be loaded.'
        this.loading = false
      }
    }
  }
}
</script>

<style scoped>
.session-view {
  min-height: 100vh;
}

.loading,
.error {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  text-align: center;
}

.loading p,
.error p {
  color: #f5f5dc;
  font-size: 24px;
  margin-bottom: 20px;
}

.error p {
  color: #ff6b6b;
}
</style>
